// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCU4EpdKxE-Hdi4waKloCfLQz0M-vJuXu0',
    appId: '1:52460152829:web:73b43ae9aeeaa9675a5b94',
    messagingSenderId: '52460152829',
    projectId: 'beetask-3906d',
    authDomain: 'beetask-3906d.firebaseapp.com',
    storageBucket: 'beetask-3906d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBRnxZ3X8-gXGaq-jIrnW1G7G-2_DyOE0',
    appId: '1:52460152829:android:9bbe365d1a5a0f375a5b94',
    messagingSenderId: '52460152829',
    projectId: 'beetask-3906d',
    storageBucket: 'beetask-3906d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDudm6eRJSkU14pA2KTm9mTTudjrspC2jc',
    appId: '1:52460152829:ios:82834d1e38087b335a5b94',
    messagingSenderId: '52460152829',
    projectId: 'beetask-3906d',
    storageBucket: 'beetask-3906d.firebasestorage.app',
    iosBundleId: 'com.example.beeTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDudm6eRJSkU14pA2KTm9mTTudjrspC2jc',
    appId: '1:52460152829:ios:82834d1e38087b335a5b94',
    messagingSenderId: '52460152829',
    projectId: 'beetask-3906d',
    storageBucket: 'beetask-3906d.firebasestorage.app',
    iosBundleId: 'com.example.beeTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCU4EpdKxE-Hdi4waKloCfLQz0M-vJuXu0',
    appId: '1:52460152829:web:fa5a6a524b53df305a5b94',
    messagingSenderId: '52460152829',
    projectId: 'beetask-3906d',
    authDomain: 'beetask-3906d.firebaseapp.com',
    storageBucket: 'beetask-3906d.firebasestorage.app',
  );
}
